trigger:
  - main
  - development

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "select sdk"
    inputs:
      packageType: "sdk"
      version: "3.1.300"
  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
      command: "restore"
      feedsToUse: "select"
  - task: DotNetCoreCLI@2
    displayName: "dotnet build"
    inputs:
      command: "build"
      arguments: "--configuration $(buildConfiguration)"
      projects: "**/*.csproj"
  - task: DotNetCoreCLI@2
    displayName: "dotnet test"
    inputs:
      command: "test"
      arguments: "/p:CollectCoverage=true"
      projects: "**/*.csproj"
  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '0'
  - task: NuGetCommand@2
    displayName: "nuget push"
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '9566de23-5df9-4be2-b676-8ac0e1cbd609/45a7e446-1e14-44f0-a847-4c60611a0413'