name: .NET Package Workflow
on:
  push:
    branches: [development, main]
  pull_request:
    branches: [feature/*, development]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SDK Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet nuget push **/*.nupkg -s https://nuget.pkg.github.com/wapplegate/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
